### ISSUE TITLE
"From " vs. ">From " Issue in .mbox File

### ISSUE THREAD

**Issue by simongamerpage** [jooyoungseo/mboxr#2]
Hello JooYoung,

As previously mentioned in an email chain, I enountered the following error when translating my .mbox file to an R tibble (replacing personal information with brackets):

Something wrong with your mbox file: **[directory/file_name.mbox]** Check the file(s) if it is formed correctly. Maybe 'From ' in the mail body has not been correctly escaped as '>From '. Refer to the following resource:
https://pymotw.com/3/mailbox/
The specific error message from Python: expected string or bytes-like object.

After looking at the tail end of the transfer, I noticed than my final line looked like this:

'From: =?utf-8?Q?POLSCI=20Advisor?= <polsci-advisor@umich.edu>'

This seems to be an issue where the function is not reading "From: " as a true "From " or ">From ". Likely, this could be fixed with a regex solution in the function?

I feel especially compelled to post this because I scraped this data from my own Google accounts for a surveillance project. Presumably, if anyone downloads their own Gmail data and desires to use this package, they will want to know about this/have this fixed to utilize the package successfully.

Thanks again, and let me know if I got anything wrong in here (only have an undergraduate degree in dealing with data science in R),

Simon Page

**Comment by jooyoungseo** [comment]
I assume that your six observations have come from the plain text file directly in the middle of your debugging process, not from the R console. Please correct me if I am wrong.

I will use the term "instance" to indicate each message unit within `mbox` text file moving forward to minimize any confusion against "observation," the general term referring to each row in a `tidy` data frame.

Please take a look at the sixth message instance causing the issue in your text editor.

```
From: =?utf-8?Q?POLSCI=20Advisor?= <
```

Is that line followed by any second trailing line with carriage return?

That line seems problematic because it has encoded character (e.g., From: =?utf-8?) not a regular plain text.

Try to strip out this line and followed trailing line as one clean plain text by referring to other non-problematic message instances.

You may wonder if my package could automatically take care of this kind of encoding issue; however, this is the original file issue outside the scope of this package support.

Please let me know if you still have any problems.

**Comment by jooyoungseo** [comment]
I am closing this issue unless there was any further problem found.
